/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicDiscoverRouteImport } from './routes/_public/discover'
import { Route as PublicGigsRouteImport } from './routes/_public/gigs'
import { Route as PublicShotsRouteImport } from './routes/_public/shots'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ApiSeedRouteImport } from './routes/api/seed'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as UploadsFileRouteImport } from './routes/uploads/$file'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as AuthAppMessagesRouteImport } from './routes/_auth/app/messages'
import { Route as AuthAppOnboardingRouteImport } from './routes/_auth/app/onboarding'
import { Route as PublicCreatorsIndexRouteImport } from './routes/_public/creators/index'
import { Route as PublicCreatorsCreatorIdRouteImport } from './routes/_public/creators/$creatorId'
import { Route as AdminReportsIndexRouteImport } from './routes/admin/reports/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthAppBookingsIndexRouteImport } from './routes/_auth/app/bookings/index'
import { Route as AuthAppEquipmentIndexRouteImport } from './routes/_auth/app/equipment/index'
import { Route as AuthAppGigsIndexRouteImport } from './routes/_auth/app/gigs/index'
import { Route as AuthAppGigsGigIdRouteImport } from './routes/_auth/app/gigs/$gigId'
import { Route as AuthAppPortfolioIndexRouteImport } from './routes/_auth/app/portfolio/index'
import { Route as AuthAppPostsIndexRouteImport } from './routes/_auth/app/posts/index'
import { Route as AuthAppProfileIndexRouteImport } from './routes/_auth/app/profile/index'
import { Route as AuthAppProfileCreatorRouteImport } from './routes/_auth/app/profile/creator'
import { Route as AuthAppServicesIndexRouteImport } from './routes/_auth/app/services/index'
import { Route as AuthAppStudioIndexRouteImport } from './routes/_auth/app/studio/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDiscoverRoute = PublicDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGigsRoute = PublicGigsRouteImport.update({
  id: '/gigs',
  path: '/gigs',
  getParentRoute: () => PublicRoute,
} as any)
const PublicShotsRoute = PublicShotsRouteImport.update({
  id: '/shots',
  path: '/shots',
  getParentRoute: () => PublicRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedRoute = ApiSeedRouteImport.update({
  id: '/api/seed',
  path: '/api/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsFileRoute = UploadsFileRouteImport.update({
  id: '/uploads/$file',
  path: '/uploads/$file',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppMessagesRoute = AuthAppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppOnboardingRoute = AuthAppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const PublicCreatorsIndexRoute = PublicCreatorsIndexRouteImport.update({
  id: '/creators/',
  path: '/creators/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCreatorsCreatorIdRoute = PublicCreatorsCreatorIdRouteImport.update({
  id: '/creators/$creatorId',
  path: '/creators/$creatorId',
  getParentRoute: () => PublicRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/admin/reports/',
  path: '/admin/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppBookingsIndexRoute = AuthAppBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppEquipmentIndexRoute = AuthAppEquipmentIndexRouteImport.update({
  id: '/equipment/',
  path: '/equipment/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppGigsIndexRoute = AuthAppGigsIndexRouteImport.update({
  id: '/gigs/',
  path: '/gigs/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppGigsGigIdRoute = AuthAppGigsGigIdRouteImport.update({
  id: '/gigs/$gigId',
  path: '/gigs/$gigId',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppPortfolioIndexRoute = AuthAppPortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppPostsIndexRoute = AuthAppPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppProfileIndexRoute = AuthAppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppProfileCreatorRoute = AuthAppProfileCreatorRouteImport.update({
  id: '/profile/creator',
  path: '/profile/creator',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppServicesIndexRoute = AuthAppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppStudioIndexRoute = AuthAppStudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/discover': typeof PublicDiscoverRoute
  '/gigs': typeof PublicGigsRoute
  '/shots': typeof PublicShotsRoute
  '/api/seed': typeof ApiSeedRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/uploads/$file': typeof UploadsFileRoute
  '/admin/': typeof AdminIndexRoute
  '/app/messages': typeof AuthAppMessagesRoute
  '/app/onboarding': typeof AuthAppOnboardingRoute
  '/creators/$creatorId': typeof PublicCreatorsCreatorIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AuthAppIndexRoute
  '/creators/': typeof PublicCreatorsIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/app/gigs/$gigId': typeof AuthAppGigsGigIdRoute
  '/app/profile/creator': typeof AuthAppProfileCreatorRoute
  '/app/bookings/': typeof AuthAppBookingsIndexRoute
  '/app/equipment/': typeof AuthAppEquipmentIndexRoute
  '/app/gigs/': typeof AuthAppGigsIndexRoute
  '/app/portfolio/': typeof AuthAppPortfolioIndexRoute
  '/app/posts/': typeof AuthAppPostsIndexRoute
  '/app/profile/': typeof AuthAppProfileIndexRoute
  '/app/services/': typeof AuthAppServicesIndexRoute
  '/app/studio/': typeof AuthAppStudioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/discover': typeof PublicDiscoverRoute
  '/gigs': typeof PublicGigsRoute
  '/shots': typeof PublicShotsRoute
  '/api/seed': typeof ApiSeedRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/uploads/$file': typeof UploadsFileRoute
  '/admin': typeof AdminIndexRoute
  '/app/messages': typeof AuthAppMessagesRoute
  '/app/onboarding': typeof AuthAppOnboardingRoute
  '/creators/$creatorId': typeof PublicCreatorsCreatorIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/creators': typeof PublicCreatorsIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/app/gigs/$gigId': typeof AuthAppGigsGigIdRoute
  '/app/profile/creator': typeof AuthAppProfileCreatorRoute
  '/app/bookings': typeof AuthAppBookingsIndexRoute
  '/app/equipment': typeof AuthAppEquipmentIndexRoute
  '/app/gigs': typeof AuthAppGigsIndexRoute
  '/app/portfolio': typeof AuthAppPortfolioIndexRoute
  '/app/posts': typeof AuthAppPostsIndexRoute
  '/app/profile': typeof AuthAppProfileIndexRoute
  '/app/services': typeof AuthAppServicesIndexRoute
  '/app/studio': typeof AuthAppStudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/_public/discover': typeof PublicDiscoverRoute
  '/_public/gigs': typeof PublicGigsRoute
  '/_public/shots': typeof PublicShotsRoute
  '/api/seed': typeof ApiSeedRoute
  '/api/uploads': typeof ApiUploadsRoute
  '/uploads/$file': typeof UploadsFileRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_auth/app/messages': typeof AuthAppMessagesRoute
  '/_auth/app/onboarding': typeof AuthAppOnboardingRoute
  '/_public/creators/$creatorId': typeof PublicCreatorsCreatorIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_public/creators/': typeof PublicCreatorsIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/_auth/app/gigs/$gigId': typeof AuthAppGigsGigIdRoute
  '/_auth/app/profile/creator': typeof AuthAppProfileCreatorRoute
  '/_auth/app/bookings/': typeof AuthAppBookingsIndexRoute
  '/_auth/app/equipment/': typeof AuthAppEquipmentIndexRoute
  '/_auth/app/gigs/': typeof AuthAppGigsIndexRoute
  '/_auth/app/portfolio/': typeof AuthAppPortfolioIndexRoute
  '/_auth/app/posts/': typeof AuthAppPostsIndexRoute
  '/_auth/app/profile/': typeof AuthAppProfileIndexRoute
  '/_auth/app/services/': typeof AuthAppServicesIndexRoute
  '/_auth/app/studio/': typeof AuthAppStudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/discover'
    | '/gigs'
    | '/shots'
    | '/api/seed'
    | '/api/uploads'
    | '/uploads/$file'
    | '/admin/'
    | '/app/messages'
    | '/app/onboarding'
    | '/creators/$creatorId'
    | '/api/auth/$'
    | '/app/'
    | '/creators/'
    | '/admin/reports/'
    | '/app/gigs/$gigId'
    | '/app/profile/creator'
    | '/app/bookings/'
    | '/app/equipment/'
    | '/app/gigs/'
    | '/app/portfolio/'
    | '/app/posts/'
    | '/app/profile/'
    | '/app/services/'
    | '/app/studio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/discover'
    | '/gigs'
    | '/shots'
    | '/api/seed'
    | '/api/uploads'
    | '/uploads/$file'
    | '/admin'
    | '/app/messages'
    | '/app/onboarding'
    | '/creators/$creatorId'
    | '/api/auth/$'
    | '/app'
    | '/creators'
    | '/admin/reports'
    | '/app/gigs/$gigId'
    | '/app/profile/creator'
    | '/app/bookings'
    | '/app/equipment'
    | '/app/gigs'
    | '/app/portfolio'
    | '/app/posts'
    | '/app/profile'
    | '/app/services'
    | '/app/studio'
  id:
    | '__root__'
    | '/_auth'
    | '/_guest'
    | '/_public'
    | '/_auth/app'
    | '/_guest/login'
    | '/_guest/signup'
    | '/_public/discover'
    | '/_public/gigs'
    | '/_public/shots'
    | '/api/seed'
    | '/api/uploads'
    | '/uploads/$file'
    | '/_public/'
    | '/admin/'
    | '/_auth/app/messages'
    | '/_auth/app/onboarding'
    | '/_public/creators/$creatorId'
    | '/api/auth/$'
    | '/_auth/app/'
    | '/_public/creators/'
    | '/admin/reports/'
    | '/_auth/app/gigs/$gigId'
    | '/_auth/app/profile/creator'
    | '/_auth/app/bookings/'
    | '/_auth/app/equipment/'
    | '/_auth/app/gigs/'
    | '/_auth/app/portfolio/'
    | '/_auth/app/posts/'
    | '/_auth/app/profile/'
    | '/_auth/app/services/'
    | '/_auth/app/studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiSeedRoute: typeof ApiSeedRoute
  ApiUploadsRoute: typeof ApiUploadsRoute
  UploadsFileRoute: typeof UploadsFileRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/discover': {
      id: '/_public/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof PublicDiscoverRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/gigs': {
      id: '/_public/gigs'
      path: '/gigs'
      fullPath: '/gigs'
      preLoaderRoute: typeof PublicGigsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/shots': {
      id: '/_public/shots'
      path: '/shots'
      fullPath: '/shots'
      preLoaderRoute: typeof PublicShotsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed': {
      id: '/api/seed'
      path: '/api/seed'
      fullPath: '/api/seed'
      preLoaderRoute: typeof ApiSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads/$file': {
      id: '/uploads/$file'
      path: '/uploads/$file'
      fullPath: '/uploads/$file'
      preLoaderRoute: typeof UploadsFileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/messages': {
      id: '/_auth/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AuthAppMessagesRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/onboarding': {
      id: '/_auth/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AuthAppOnboardingRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_public/creators/': {
      id: '/_public/creators/'
      path: '/creators'
      fullPath: '/creators/'
      preLoaderRoute: typeof PublicCreatorsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/creators/$creatorId': {
      id: '/_public/creators/$creatorId'
      path: '/creators/$creatorId'
      fullPath: '/creators/$creatorId'
      preLoaderRoute: typeof PublicCreatorsCreatorIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/admin/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/bookings/': {
      id: '/_auth/app/bookings/'
      path: '/bookings'
      fullPath: '/app/bookings/'
      preLoaderRoute: typeof AuthAppBookingsIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/equipment/': {
      id: '/_auth/app/equipment/'
      path: '/equipment'
      fullPath: '/app/equipment/'
      preLoaderRoute: typeof AuthAppEquipmentIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/gigs/': {
      id: '/_auth/app/gigs/'
      path: '/gigs'
      fullPath: '/app/gigs/'
      preLoaderRoute: typeof AuthAppGigsIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/gigs/$gigId': {
      id: '/_auth/app/gigs/$gigId'
      path: '/gigs/$gigId'
      fullPath: '/app/gigs/$gigId'
      preLoaderRoute: typeof AuthAppGigsGigIdRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/portfolio/': {
      id: '/_auth/app/portfolio/'
      path: '/portfolio'
      fullPath: '/app/portfolio/'
      preLoaderRoute: typeof AuthAppPortfolioIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/posts/': {
      id: '/_auth/app/posts/'
      path: '/posts'
      fullPath: '/app/posts/'
      preLoaderRoute: typeof AuthAppPostsIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/profile/': {
      id: '/_auth/app/profile/'
      path: '/profile'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AuthAppProfileIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/profile/creator': {
      id: '/_auth/app/profile/creator'
      path: '/profile/creator'
      fullPath: '/app/profile/creator'
      preLoaderRoute: typeof AuthAppProfileCreatorRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/services/': {
      id: '/_auth/app/services/'
      path: '/services'
      fullPath: '/app/services/'
      preLoaderRoute: typeof AuthAppServicesIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/studio/': {
      id: '/_auth/app/studio/'
      path: '/studio'
      fullPath: '/app/studio/'
      preLoaderRoute: typeof AuthAppStudioIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
  }
}

interface AuthAppRouteRouteChildren {
  AuthAppMessagesRoute: typeof AuthAppMessagesRoute
  AuthAppOnboardingRoute: typeof AuthAppOnboardingRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthAppGigsGigIdRoute: typeof AuthAppGigsGigIdRoute
  AuthAppProfileCreatorRoute: typeof AuthAppProfileCreatorRoute
  AuthAppBookingsIndexRoute: typeof AuthAppBookingsIndexRoute
  AuthAppEquipmentIndexRoute: typeof AuthAppEquipmentIndexRoute
  AuthAppGigsIndexRoute: typeof AuthAppGigsIndexRoute
  AuthAppPortfolioIndexRoute: typeof AuthAppPortfolioIndexRoute
  AuthAppPostsIndexRoute: typeof AuthAppPostsIndexRoute
  AuthAppProfileIndexRoute: typeof AuthAppProfileIndexRoute
  AuthAppServicesIndexRoute: typeof AuthAppServicesIndexRoute
  AuthAppStudioIndexRoute: typeof AuthAppStudioIndexRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppMessagesRoute: AuthAppMessagesRoute,
  AuthAppOnboardingRoute: AuthAppOnboardingRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthAppGigsGigIdRoute: AuthAppGigsGigIdRoute,
  AuthAppProfileCreatorRoute: AuthAppProfileCreatorRoute,
  AuthAppBookingsIndexRoute: AuthAppBookingsIndexRoute,
  AuthAppEquipmentIndexRoute: AuthAppEquipmentIndexRoute,
  AuthAppGigsIndexRoute: AuthAppGigsIndexRoute,
  AuthAppPortfolioIndexRoute: AuthAppPortfolioIndexRoute,
  AuthAppPostsIndexRoute: AuthAppPostsIndexRoute,
  AuthAppProfileIndexRoute: AuthAppProfileIndexRoute,
  AuthAppServicesIndexRoute: AuthAppServicesIndexRoute,
  AuthAppStudioIndexRoute: AuthAppStudioIndexRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

interface PublicRouteChildren {
  PublicDiscoverRoute: typeof PublicDiscoverRoute
  PublicGigsRoute: typeof PublicGigsRoute
  PublicShotsRoute: typeof PublicShotsRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicCreatorsCreatorIdRoute: typeof PublicCreatorsCreatorIdRoute
  PublicCreatorsIndexRoute: typeof PublicCreatorsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicDiscoverRoute: PublicDiscoverRoute,
  PublicGigsRoute: PublicGigsRoute,
  PublicShotsRoute: PublicShotsRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicCreatorsCreatorIdRoute: PublicCreatorsCreatorIdRoute,
  PublicCreatorsIndexRoute: PublicCreatorsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiSeedRoute: ApiSeedRoute,
  ApiUploadsRoute: ApiUploadsRoute,
  UploadsFileRoute: UploadsFileRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
