/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as GuestRouteRouteImport } from './routes/_guest/route'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ShotsRouteImport } from './routes/shots'
import { Route as AuthAppRouteRouteImport } from './routes/_auth/app/route'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as GuestSignupRouteImport } from './routes/_guest/signup'
import { Route as CreatorsCreatorIdRouteImport } from './routes/creators/$creatorId'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthAppBookingsIndexRouteImport } from './routes/_auth/app/bookings/index'
import { Route as AuthAppEquipmentIndexRouteImport } from './routes/_auth/app/equipment/index'
import { Route as AuthAppPortfolioIndexRouteImport } from './routes/_auth/app/portfolio/index'
import { Route as AuthAppPostsIndexRouteImport } from './routes/_auth/app/posts/index'
import { Route as AuthAppProfileIndexRouteImport } from './routes/_auth/app/profile/index'
import { Route as AuthAppProfileCreatorRouteImport } from './routes/_auth/app/profile/creator'
import { Route as AuthAppServicesIndexRouteImport } from './routes/_auth/app/services/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRouteRoute = GuestRouteRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ShotsRoute = ShotsRouteImport.update({
  id: '/shots',
  path: '/shots',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRouteRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRouteRoute,
} as any)
const GuestSignupRoute = GuestSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => GuestRouteRoute,
} as any)
const CreatorsCreatorIdRoute = CreatorsCreatorIdRouteImport.update({
  id: '/creators/$creatorId',
  path: '/creators/$creatorId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppBookingsIndexRoute = AuthAppBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppEquipmentIndexRoute = AuthAppEquipmentIndexRouteImport.update({
  id: '/equipment/',
  path: '/equipment/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppPortfolioIndexRoute = AuthAppPortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppPostsIndexRoute = AuthAppPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppProfileIndexRoute = AuthAppProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppProfileCreatorRoute = AuthAppProfileCreatorRouteImport.update({
  id: '/profile/creator',
  path: '/profile/creator',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppServicesIndexRoute = AuthAppServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => AuthAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/shots': typeof ShotsRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/creators/$creatorId': typeof CreatorsCreatorIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AuthAppIndexRoute
  '/app/profile/creator': typeof AuthAppProfileCreatorRoute
  '/app/bookings/': typeof AuthAppBookingsIndexRoute
  '/app/equipment/': typeof AuthAppEquipmentIndexRoute
  '/app/portfolio/': typeof AuthAppPortfolioIndexRoute
  '/app/posts/': typeof AuthAppPostsIndexRoute
  '/app/profile/': typeof AuthAppProfileIndexRoute
  '/app/services/': typeof AuthAppServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/shots': typeof ShotsRoute
  '/login': typeof GuestLoginRoute
  '/signup': typeof GuestSignupRoute
  '/creators/$creatorId': typeof CreatorsCreatorIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/app/profile/creator': typeof AuthAppProfileCreatorRoute
  '/app/bookings': typeof AuthAppBookingsIndexRoute
  '/app/equipment': typeof AuthAppEquipmentIndexRoute
  '/app/portfolio': typeof AuthAppPortfolioIndexRoute
  '/app/posts': typeof AuthAppPostsIndexRoute
  '/app/profile': typeof AuthAppProfileIndexRoute
  '/app/services': typeof AuthAppServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_guest': typeof GuestRouteRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/shots': typeof ShotsRoute
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/signup': typeof GuestSignupRoute
  '/creators/$creatorId': typeof CreatorsCreatorIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/app/profile/creator': typeof AuthAppProfileCreatorRoute
  '/_auth/app/bookings/': typeof AuthAppBookingsIndexRoute
  '/_auth/app/equipment/': typeof AuthAppEquipmentIndexRoute
  '/_auth/app/portfolio/': typeof AuthAppPortfolioIndexRoute
  '/_auth/app/posts/': typeof AuthAppPostsIndexRoute
  '/_auth/app/profile/': typeof AuthAppProfileIndexRoute
  '/_auth/app/services/': typeof AuthAppServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/discover'
    | '/shots'
    | '/app'
    | '/login'
    | '/signup'
    | '/creators/$creatorId'
    | '/api/auth/$'
    | '/app/'
    | '/app/profile/creator'
    | '/app/bookings/'
    | '/app/equipment/'
    | '/app/portfolio/'
    | '/app/posts/'
    | '/app/profile/'
    | '/app/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/discover'
    | '/shots'
    | '/login'
    | '/signup'
    | '/creators/$creatorId'
    | '/api/auth/$'
    | '/app'
    | '/app/profile/creator'
    | '/app/bookings'
    | '/app/equipment'
    | '/app/portfolio'
    | '/app/posts'
    | '/app/profile'
    | '/app/services'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_guest'
    | '/discover'
    | '/shots'
    | '/_auth/app'
    | '/_guest/login'
    | '/_guest/signup'
    | '/creators/$creatorId'
    | '/api/auth/$'
    | '/_auth/app/'
    | '/_auth/app/profile/creator'
    | '/_auth/app/bookings/'
    | '/_auth/app/equipment/'
    | '/_auth/app/portfolio/'
    | '/_auth/app/posts/'
    | '/_auth/app/profile/'
    | '/_auth/app/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  GuestRouteRoute: typeof GuestRouteRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  ShotsRoute: typeof ShotsRoute
  CreatorsCreatorIdRoute: typeof CreatorsCreatorIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shots': {
      id: '/shots'
      path: '/shots'
      fullPath: '/shots'
      preLoaderRoute: typeof ShotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/_guest/signup': {
      id: '/_guest/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof GuestSignupRouteImport
      parentRoute: typeof GuestRouteRoute
    }
    '/creators/$creatorId': {
      id: '/creators/$creatorId'
      path: '/creators/$creatorId'
      fullPath: '/creators/$creatorId'
      preLoaderRoute: typeof CreatorsCreatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/bookings/': {
      id: '/_auth/app/bookings/'
      path: '/bookings'
      fullPath: '/app/bookings/'
      preLoaderRoute: typeof AuthAppBookingsIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/equipment/': {
      id: '/_auth/app/equipment/'
      path: '/equipment'
      fullPath: '/app/equipment/'
      preLoaderRoute: typeof AuthAppEquipmentIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/portfolio/': {
      id: '/_auth/app/portfolio/'
      path: '/portfolio'
      fullPath: '/app/portfolio/'
      preLoaderRoute: typeof AuthAppPortfolioIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/posts/': {
      id: '/_auth/app/posts/'
      path: '/posts'
      fullPath: '/app/posts/'
      preLoaderRoute: typeof AuthAppPostsIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/profile/': {
      id: '/_auth/app/profile/'
      path: '/profile'
      fullPath: '/app/profile/'
      preLoaderRoute: typeof AuthAppProfileIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/profile/creator': {
      id: '/_auth/app/profile/creator'
      path: '/profile/creator'
      fullPath: '/app/profile/creator'
      preLoaderRoute: typeof AuthAppProfileCreatorRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/services/': {
      id: '/_auth/app/services/'
      path: '/services'
      fullPath: '/app/services/'
      preLoaderRoute: typeof AuthAppServicesIndexRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
  }
}

interface AuthAppRouteRouteChildren {
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthAppProfileCreatorRoute: typeof AuthAppProfileCreatorRoute
  AuthAppBookingsIndexRoute: typeof AuthAppBookingsIndexRoute
  AuthAppEquipmentIndexRoute: typeof AuthAppEquipmentIndexRoute
  AuthAppPortfolioIndexRoute: typeof AuthAppPortfolioIndexRoute
  AuthAppPostsIndexRoute: typeof AuthAppPostsIndexRoute
  AuthAppProfileIndexRoute: typeof AuthAppProfileIndexRoute
  AuthAppServicesIndexRoute: typeof AuthAppServicesIndexRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthAppProfileCreatorRoute: AuthAppProfileCreatorRoute,
  AuthAppBookingsIndexRoute: AuthAppBookingsIndexRoute,
  AuthAppEquipmentIndexRoute: AuthAppEquipmentIndexRoute,
  AuthAppPortfolioIndexRoute: AuthAppPortfolioIndexRoute,
  AuthAppPostsIndexRoute: AuthAppPostsIndexRoute,
  AuthAppProfileIndexRoute: AuthAppProfileIndexRoute,
  AuthAppServicesIndexRoute: AuthAppServicesIndexRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface GuestRouteRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestSignupRoute: typeof GuestSignupRoute
}

const GuestRouteRouteChildren: GuestRouteRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestSignupRoute: GuestSignupRoute,
}

const GuestRouteRouteWithChildren = GuestRouteRoute._addFileChildren(
  GuestRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  GuestRouteRoute: GuestRouteRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  ShotsRoute: ShotsRoute,
  CreatorsCreatorIdRoute: CreatorsCreatorIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
