import { createReadStream } from "node:fs";
import { mkdir, rm, stat, writeFile } from "node:fs/promises";
import { dirname, join, resolve, sep } from "node:path";
import { Readable } from "node:stream";

import { ENV } from "varlock/env";

import { sniffImageType } from "#/lib/uploads/sniff.ts";

/**
 * Where uploaded bytes live.
 *
 * The driver is the only thing that knows how to put a file away and get it back, so swapping in S3
 * or R2 later is a matter of a second implementation rather than a change at every call site.
 */
export interface StorageDriver {
  put(key: string, bytes: Uint8Array): Promise<void>;
  getStream(key: string): Promise<ReadableStream<Uint8Array>>;
  remove(key: string): Promise<void>;
}

const KEY_PATTERN = /^\d{4}-\d{2}-\w{8}-\w{4}-\w{4}-\w{4}-\w{12}\.\w+$/;

/** Keys are generated by `buildStorageKey`, so anything else is a probing attempt. */
export function assertUsableKey(key: string): void {
  if (!KEY_PATTERN.test(key)) {
    throw new Error("Unknown upload key.");
  }
}

class LocalDriver implements StorageDriver {
  constructor(private readonly root: string) {}

  /** Resolves a key to a path and proves the result is still inside the root. */
  private pathFor(key: string): string {
    assertUsableKey(key);
    const path = resolve(join(this.root, key));
    if (path !== this.root && !path.startsWith(this.root + sep)) {
      throw new Error("Unknown upload key.");
    }
    return path;
  }

  async put(key: string, bytes: Uint8Array): Promise<void> {
    const path = this.pathFor(key);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, bytes);
  }

  async getStream(key: string): Promise<ReadableStream<Uint8Array>> {
    const path = this.pathFor(key);
    await stat(path); // Throws ENOENT for a key that was never uploaded or has been removed.
    return Readable.toWeb(createReadStream(path)) as ReadableStream<Uint8Array>;
  }

  async remove(key: string): Promise<void> {
    await rm(this.pathFor(key), { force: true });
  }
}

/**
 * Uploads go under `.data/uploads` rather than `public/`.
 *
 * A production build snapshots `public/` at build time, so a file written there at runtime would
 * 404 — and a user-supplied path inside the app's own asset directory is a bad idea regardless. The
 * files are served by `/uploads/[...key]` instead.
 */
function localDriver(): StorageDriver {
  return new LocalDriver(join(process.cwd(), ENV.UPLOAD_DIR ?? ".data/uploads"));
}

let driver: StorageDriver | undefined;

/** Resolved per call rather than at import so tests can point it somewhere disposable. */
export function getStorage(): StorageDriver {
  if (ENV.UPLOAD_DRIVER === "local") {
    return (driver ??= localDriver());
  }
  throw new Error(`Unsupported upload driver "${ENV.UPLOAD_DRIVER}".`);
}

/** Only used by tests, to start from an empty directory. */
export function setStorageForTesting(replacement?: StorageDriver): void {
  driver = replacement;
}

/** The content type to serve a stored file with, from its key. */
export function contentTypeForKey(key: string): string | null {
  const extension = key.slice(key.lastIndexOf(".") + 1);
  return (
    [
      ["jpg", "image/jpeg"],
      ["png", "image/png"],
      ["webp", "image/webp"],
      ["avif", "image/avif"],
    ].find(([ext]) => ext === extension)?.[1] ?? null
  );
}

/** Exposed so callers can agree with the sniffer about what a key means. */
export { sniffImageType };
